import Head from "next/head";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";
import Products from "../components/products";
import { Gallary } from "../styles/Gallary";

export default function Home() {
  //fetch products from strapi

  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  //check for data coming in

  if (fetching) return <p> Loading ...</p>;
  if (error) return <p> Error {error.message}</p>;

  const products = data.products.data;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Gallary>
          {products.map((product) => (
            <Products key={product.attributes.Slug} product={product} />
          ))}
        </Gallary>
      </main>
    </>
  );
}
